config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :users, only: [:show, :search] do
    resources :trips, only: [:index, :show, :new, :create, :update, :destroy] do
      resources :tips, only: [:index, :show, :new, :create, :update, :destroy]
    end
  end

  scope :users do
    get 'search/:q' => 'users#search'
    post ':id/friends' => 'friendships#create'
    get ':id/friends/pending' => 'friendships#pending'
    put ':id/friends/:friend_id' => 'friendships#confirm'
    delete ':id/friends/:friend_id' => 'friendships#destroy'
  end

  root to: "home#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :friend1, :class_name => :User, :foreign_key => "friend1_id"
  belongs_to :friend2, :class_name => :User, :foreign_key => "friend2_id"
end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :trip
  validates_uniqueness_of :place_id, scope: :trip_id, message: "Trip already contains location"

end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :tips

  validates :name, :center, :zoom, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips
  has_many :tips, through: :trips
  has_many :friendships, :class_name => :Friendship, :foreign_key => "friend1_id"


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def friends
    friends = []
    Friendship.where("friend1_id = ? and confirmed = ?", self.id, true).each{|x|friends << x.friend2}
    Friendship.where("friend2_id = ? and confirmed = ?", self.id, true).each{|x|friends << x.friend1}
    return friends
  end

  def unconfirmed_friends
    friends = []
    Friendship.where("friend1_id = ? and confirmed = ?", self.id, false).each{|x|friends << x.friend2}
    return friends
  end

  def friend_requests
    friends = []
    Friendship.where("friend2_id = ? and confirmed = ?", self.id, false).each{|x|friends << x.friend1}
    return friends
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ActionController::Base
  def create
    user = User.find(params[:id])
    friend = User.find_by(name: params[:name])
    request = Friendship.new(friend1: user, friend2: friend)
    if request.save
      render json: user
    end
  end

  def pending
    user = User.find(params[:id])
    render json: user.friend_requests
  end

  def confirm
    friendship = Friendship.find_by(friend1: params[:friend_id], friend2: params[:id])
    friendship.confirmed = true
    friendship.save
    render json: {friend: friendship.friend1, trips: friendship.friend1.trips}
  end

  def destroy
    friendship = Friendship.find_by(friend1: params[:friend_id], friend2: params[:id])
    Friendship.delete(friendship.id)
    render json: friendship
  end

  private

  def friendship_params
      params.require(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  def index
    @user_id = session[:user_id]
    @user = User.find_by(id: params[:user_id])
    @trip = @user.trips.find_by(id: params[:trip_id])
    @tips = @trip.tips.as_json

    @tips.each do |tip|
      tip["user_id"] = @user.id
      tip["username"] = @user.name.split.first
      if tip['comment'] == "" || tip['comment'].nil?
        tip["comment_icon"] = 'hidden'
      else
        tip["comment_icon"] = ""
      end
    end

    respond_to do |format|
      format.html { render :index, :layout => false }
      format.json { render json: @tips }
    end
  end

  def show
    @current_user = session[:user_id]
    @user = User.find_by(id: params[:user_id])
    @trip = @user.trips.find_by(id: params[:trip_id])
    @tip = @trip.tips.find_by(id: params[:id])

    @tip_json = @tip.as_json
    @tip_json["user_id"] = @user.id
    @tip_json["username"] = @user.name.split.first
    if @tip["comment"] == "" || @tip["comment"].nil?
      @tip_json["comment_icon"] = 'hidden'
    else
      @tip_json["comment_icon"] = ""
    end

    respond_to do |format|
      format.html { render :show, :layout => false }
      format.json { render json: @tip_json }
    end
  end

  def create
    @user = User.find_by(id: params[:user_id])
    @trip = @user.trips.find_by(id: params[:trip_id])
    @tip = @trip.tips.create(tip_params)

    if @tip.save
      redirect_to user_trip_tip_path(@user,@trip,@tip)
    else
      render json: @tip.errors, status: :unprocessable_entity
    end
  end

  def update
    @current_user = session[:user_id]
    @user = User.find_by(id: params[:user_id])
    @trip = @user.trips.find_by(id: params[:trip_id])
    @tip = @trip.tips.find_by(id: params[:id])
    @tip.update_attributes(tip_params)

    if @tip.save
      render :show, :layout => false
    else
      render json: @tip.errors, status: :unprocessable_entity
    end
  end

  def destroy
    Tip.destroy(params[:id])
  end

  private

  def tip_params
    params.require(:tip).permit( :name, :place_id, :rating, :comment, :lat, :lng, :address, :g_rating )
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @user = User.find_by(id: params[:user_id])
    @trips = @user.trips if @user
    render json: @trips, status: :created
  end

  def show
    @user = User.find_by(id: params[:user_id])
    @trip = @user.trips.find_by(id: params[:id]) if @user
    render json: @trip, status: :created
  end

  def create
    @user = User.find_by(id: params[:user_id])
    @trip = @user.trips.create(trip_params)

    if @trip.save
      render json: @trip, status: :created
    else
      render json: @trip.errors, status: :unprocessable_entity
    end
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update_attributes(trip_params)
    render json: @trip
  end

  def destroy
    Trip.destroy(params[:id])
  end

  private

  def trip_params
    params.require(:trip).permit( :name, :center, :zoom, :private)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    render json: []
  end

  def search
    q = params[:q]
    if q != ""
      @user = User.find(session[:user_id])
      @friends = @user.friends
      @unconfirmed = @user.unconfirmed_friends
      @requests = @user.friend_requests
      query = "%#{q}%"
      results = User.where('lower(name) LIKE ?', query.downcase).all
      @users = []
      results.each do |x|
        @users << {:id => x.id, :name => x.name} if !@friends.include?(x) && x != @user && !@unconfirmed.include?(x) && !@requests.include?(x)
      end
      render json: @users
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tips_helper.rb
module TipsHelper

  def format_rating

    if @tip.rating == nil
      rating = "You have not rated this location yet"
    else
      rating = @tip.rating.to_s
    end

    @user.name.split.first + "'s Rating: "
  end

  def format_comment

    if @tip.comment == nil
      ""
    else
      @tip.comment
    end

  end

  def user_owned
    @current_user == @user.id
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/show.html.erb
<% if session[:user_id] %>
<% @user = User.find(session[:user_id]) %>
<div id="sidebar" role="navigation">
  <p id="welcome">Hi, <%=@user.name.split(' ')[0]%>!</p>
  <%= link_to "Sign out", signout_path, id: "sign_out"%>
    <%= image_tag('TripTip_Logo-01') %>
    <ul id='nav'>
        <li id='user-home'>
            <!-- <h1><%= @user.name%></h1> -->
        </li>

        <li id='trips-section'>
        <li id='trips-title'>
            <a id="all-trips" href="#">
              <div id="trips-header">Trips</div>
              <i id="trips-dropdown" class="fa fa-sort-desc" aria-hidden="true"></i>
              <%= button_tag(type: "button", class: 'add-trip-button') do %>
                <i class="fa fa-plus-square" aria-hidden="true"></i>
                add
              <% end %>
            </a>
            <div class="t-underline"></div>
        </li>
        <ul id="user-trips" class="hidden">
            <li>
                <%= form_tag("/users/#{@user.id}/trips", :class => 'new-trip hidden', method: "post") do %>
                  <%= text_field_tag("trip[name]", "", required: 'true') %>
                  <%= hidden_field_tag("user[id]", @user.id) %>
                  <%= hidden_field_tag("trip[center]", "3245678") %>
                  <%= hidden_field_tag("trip[zoom]", "12") %>
                  <%= button_tag(type: "submit", class: 'add-trip-submit') do %>
                            <%= content_tag(:strong, '+') %>
                    <!-- <i class="fa fa-plus-square" aria-hidden="true"></i> -->
                  <% end %>
                  <div id="private-check">
                    <%= check_box_tag :private %> private
                  </div>
                <% end %>
            </li>

            <li id="trip-template" class="trip-items sub-li hidden"><a class="trip-map" href="#"></a>
              <span class="trip-edits">
                <a class="trip-delete" href="#" rel="nofollow"><i class="fa fa-times" aria-hidden="true"></i></a>
                <a class="trip-update" href="#" rel="nofollow"><i class="fa fa-pencil" aria-hidden="true"></i></a>
              </span>
            </li>

            <form id="">

            </form>

            <% if @user.trips.length != 0 %>
            <% @user.trips.reverse.each do |x| %>
            <li class='trip-items'>
              <%= link_to x.name, user_trip_path(@user, x), class: "trip-map" %>
              <span class="trip-edits">
                <a class="trip-delete" href="/users/<%=@user.id%>/trips/<%=x.id%>" rel="nofollow"><i class="fa fa-times" aria-hidden="true"></i></a>
                <a class="trip-update" href="/users/<%=@user.id%>/trips/<%=x.id%>" rel="nofollow"><i class="fa fa-pencil" aria-hidden="true"></i></a>
              </span>

            </li>
            <% end %>
            <% end %>
        </ul>
    </li>

    <li id='friends-section'>
    <li id="friend-list">
        <a href="#">
          <div id="friends-header">Friends</div>
          <i class="fa fa-sort-desc" aria-hidden="true"></i>
          <%= button_tag(type: "button", class: 'add-friend-button') do %>
            <i class="fa fa-plus-square" aria-hidden="true"></i>
            add
          <% end %>
        </a>
        <div class="f-underline"></div>
    </li>
    <ul id='add-friends-section' class="hidden">
      <li>
        <li id='search' class="hidden">
          <div class="wrapper">
            <%= text_field_tag("search[name]", '', required: 'true', placeholder: 'Jane Doe') %>
            <i id="friend-search-icon" class="fa fa-search" aria-hidden="true"></i>
            <i id="search-close" class="fa fa-times-circle" aria-hidden="true"></i>

          </div>
        </li>
        <li id='query-results'>
        </li>
      </li>
    </ul>
    <ul id="pending" class="hidden">
    </ul>
    <ul id="friends" class="hidden">
        <% if @user.friends.length != 0 %>
          <li><h4>Friends</h4></li>
          <% @user.friends.reverse.each do |x| %>
            <li id="friend-name">
              <%= link_to x.name, user_trips_path(x), :class => 'friend-li', :data => x.id %>
              <% if x.trips.length != 0 %>
              <ul class="friend-trips hidden">
              <% x.trips.each do |t| %>
                <% if !t.private %>
                  <li class='trip-items'>
                    <%= link_to t.name, user_trip_path(x, t), :class => 'sub-li trip-map', :data => x.id %>
                  </li>
                <% end %>
              <% end %>
              </ul>
            <% else %>
              <!-- <li style="font-size: .5em"><%= x.name %> doesn't have any trips!</li> -->
            <% end %>
            </li>
          <% end %>
        <% else %>
            <li class="no-friends"><p>You don't have any friends</p></li>
        <% end %>

      </ul>
    </li>
  </ul>

</div>
<div id="message" class="hidden"></div>
  <input id="pac-input" class="controls" type="text"
    placeholder="Enter a location">
    <div class="map-container">
      <div id="map"></div>
    </div>
    <div id="ex1" style="display:none;">
        <div id='modal-html'></div>
    </div>
    <% else %>
    <section class="one">
  <nav class="navbar">
    <ul>
      <!-- <li><a href="#">fb-login</a></li>
      <li><a href="#">google-login</a></li> -->
    </ul>
  </nav>
  <!-- <h1 class="logo">TripTip</h1> -->
  <div class="logo">
    <%= image_tag('TripTip_Logo-01') %>
  </div>

</section>
<section class="content-one">
  <h1>About TripTip:</h1>
  <br>
  <p>
    TripTip is a social website to share your favorite destinations with your friends.
  </p>
  <p>
    With Google integration, you can log in and seamlessly create trips and tag each destination on your trip with a tip comment and rating.
  </p>

</section>
<section class="two">
  <h1>Connect with your friends!</h1>
  <br>
  <p>
    TripTip is an excellent way to keep in touch with your friends around the world - see all the destinations they have visited and locations they loved!
  </p>
  <p>
    Not into the social scene? Set a trip as private so your friends can't view it.
  </p>
  <br>
</section>
<section class="content-two">


</section>
<section class="three">
  <h1>About the Developers:</h1><br>
  <p>TripTip is a project created by <a href="https://github.com/linamacromer/">Lina Ma Cromer</a>, <a href="https://github.com/ap2539">Alex Perez</a>, <a href="https://github.com/bulicekj/">Jason Bulicek</a>, and <a href="https://github.com/ratley/">Bradley Inniss</a>. Comments, questions, and issues can be posted on the <a href="https://github.com/linamacromer/triptip">source site</a>.</p>

</section>
<!-- <section class="content-three">

</section> -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripTip</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://use.fontawesome.com/83561660c5.js"></script>
    <%= stylesheet_link_tag    "application", media: "all"%>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script type="text/html" id="tip-nav-partial">
      <li class="tip-item">
        <a data-place_id="{{place_id}}" href='/users/{{user_id}}/trips/{{trip_id}}/tips/{{id}}'>{{name}}</a>
      </li>
    </script>
    <script type="text/html" id="tip-partial">
      <div id='map-info-box'>
        <h3 id='info-box-title'><a href="#ex1" rel="modal:open" name='/users/{{user_id}}/trips/{{trip_id}}/tips/{{id}}'>{{name}}</a></h3>
        <ul id='info-box-list'>
          <li id='info-box-address'>{{address}}</li>
          <li id='info-box-g_rating'>Google Rating: {{g_rating}}</li>
          <li id='info-box-rating'>{{username}}'s Rating: <span>{{rating}}</span></li>
          <li id='info-box-comment'><i class="fa fa-sticky-note-o {{comment_icon}}" aria-hidden="true"></i></i></li>
        </ul>
      </div>
    </script>
  </head>
  <body>
    <div class="login">
      <% if current_user %>
         <!-- Signed in as <strong><%= current_user.name %></strong>! -->
         <!-- <%= link_to "Sign out", signout_path, id: "sign_out"%> -->
       <% else %>
         <%= link_to image_tag('sign-in-with-google'), "/auth/google_oauth2", id: "sign_in"%>
      <% end %>
    </div>
    <div>
    <%= yield %>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDr1YztyN-tIYSsmsZszIsc3VwP7c8nyRI&libraries=places&callback=initMap"
    async defer></script>
  </body>
</html>

app/views/tips/index.html.erb
<li id='tip-section'>
  <div id="tip-header">
    <span id=''><strong><%= @trip.name %></strong> - Tips</span>
    <span class="tip-controls">
      <a class="tip-section-close" href="#" rel="nofollow"><i id="tip-close" class="fa fa-times" aria-hidden="true"></i></a>
    </span>
  </div>
  <ul id='tip-list'>
    <% if @trip.tips.length != 0 %>
    <% @trip.tips.reverse.each do |x| %>
      <li class="tip-item"><%= link_to x.name, user_trip_tip_path(@user, @trip, x), "data-place_id" => x.place_id  %></li>
    <% end %>
    <% end %>
  </ul>
  <div class='hidden'>
  <% if session[:user_id] == @user.id %>
    <%= form_tag("/users/#{@user.id}/trips/#{@trip.id}/tips", :id => 'add-tip-form', :class => 'hidden', method: "post") do %>
      <%= hidden_field_tag("tip[name]") %>
      <%= hidden_field_tag("tip[place_id]") %>
      <%= hidden_field_tag("tip[lat]") %>
      <%= hidden_field_tag("tip[lng]") %>
      <%= hidden_field_tag("tip[address]") %>
      <%= hidden_field_tag("tip[g_rating]") %>
      <%= submit_tag("add") %>
    <% end %>
  <% end %>
  </div>
</li>

app/views/tips/show.html.erb
<div id='large-info-box'>
  <h1 id='large-info-trip-name'><%= @trip.name %></h1>
  <h2 id='large-info-tip-name'><%= @tip.name %></h2>

  <%= form_tag("/users/#{@user.id}/trips/#{@trip.id}/tips/#{@tip.id}", method: "put", class: "large-modal") do %>
    <div id='large-info-address'><%= @tip.address %></div>
    <br>
    <div id='large-info-rating'>
      <span id="format-rating"><%= format_rating %></span>
      <% if user_owned %>
      <fieldset class="rating user">
          <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
          <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
          <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
          <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
          <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
      </fieldset>
      <script type="text/javascript">
        $('.user #star<%=@tip.rating.to_s%>').click()
      </script>
        <%= select_tag "tip[rating]", options_for_select(['0','1','2','3','4','5'], { :class => 'hidden', :selected => @tip.rating.to_s}) %>
      <% else %>
      <fieldset class="rating user">
          <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
          <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
          <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
          <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
          <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
      </fieldset>
      <script type="text/javascript">
        $('#star<%=@tip.rating.to_s%>').click()
        $(".user input").attr("disabled", true);
      </script>
      <% end %>
    </div>
    <br>
    <br>
    <div id='large-info-rating'>
    <% if @tip.g_rating.nil? %>
      <span id="format-rating">Google+ Rating: N/A</span>
      <% else %>
      <span id="format-rating">Google+ Rating: </span>
      <fieldset class="random google">
          <input type="radio" id="gstar5" name="grating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
          <input type="radio" id="gstar4" name="grating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
          <input type="radio" id="gstar3" name="grating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
          <input type="radio" id="gstar2" name="grating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
          <input type="radio" id="gstar1" name="grating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
      </fieldset>
      <script type="text/javascript">
        $('.google #gstar<%=@tip.g_rating.round%>').click()
        $(".google input").attr("disabled", true);
      </script>
      <% end %>
    </div>
    <br>
    <br>
    <div id='large-info-comment'>
      <span>Comment:</span>
      <br>
    <% if user_owned %>
      <%= text_area_tag(:message, format_comment , size: "50x10", name: 'tip[comment]', placeholder: "Enter a comment!") %>
    </div>
      <%= submit_tag("Update") %>
      <span class="large-info-updated hidden">Updated!</span>
    <% else %>
      <p><%=@tip.comment%></p>
    <% end %>
  <% end %>
</div>

<!-- $('#tip_rating option[value=0]').attr('selected', 'selected').parent().focus() -->

app/views/users/show.html.erb
<div id='map-container'style='width: 800px;'>    
  <div id="map"></div>   
</div>